Models/comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public string comments { get; set; }
        public string comment_data { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual book book { get; set; }
        public virtual user user { get; set; }
    }
}

Areas/Admin/Controllers/commentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using PagedList;

namespace Library.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admins")]
    public class commentsController : Controller
    {
        private LibraryDBContext db = new LibraryDBContext();

        public JsonResult GetComments(string term)     // get Get Comments name with AutoComplete With jQuery UI
        {
            List<string> comments = db.comments.Where(x => x.comments.ToLower().TrimStart().StartsWith(term)).Select(y => y.comments).ToList();

            return Json(comments, JsonRequestBehavior.AllowGet);
        }

        // GET: Admin/comments
        public ActionResult Index(string search, int? page)
        {
            var comments = db.comments.AsQueryable(); // to allow filter in data (Where(....)) and store it in Var

            if (search != null)
            {
                comments = comments.Where(x => x.comments.ToLower().Contains(search));
            }

            comments = comments.Include(c => c.book).Include(c => c.user);
            return View(comments.ToList().ToPagedList(page ?? 1, 8));
        }

        // GET: Admin/comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comment comment = db.comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Admin/comments/Create
        public ActionResult Create()
        {
            ViewBag.book_id = new SelectList(db.books, "book_id", "title");
            ViewBag.user_id = new SelectList(db.users, "Id", "first_name");
            return View();
        }

        // POST: Admin/comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "comment_id,comments,book_id,user_id")] comment comment)
        {
            comment.comment_data = DateTime.Now.ToString();
            if (ModelState.IsValid)
            {
                db.comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.book_id = new SelectList(db.books, "book_id", "title", comment.book_id);
            ViewBag.user_id = new SelectList(db.users, "Id", "first_name", comment.user_id);
            return View(comment);
        }

        // GET: Admin/comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            comment comment = db.comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.book_id = new SelectList(db.books, "book_id", "title", comment.book_id);
            ViewBag.user_id = new SelectList(db.users, "Id", "first_name", comment.user_id);
            return View(comment);
        }

        // POST: Admin/comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "comment_id,comments,book_id,user_id")] comment comment)
        {
            comment.comment_data = db.comments.Find(comment.comment_id).comment_data;
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.book_id = new SelectList(db.books, "book_id", "title", comment.book_id);
            ViewBag.user_id = new SelectList(db.users, "Id", "first_name", comment.user_id);
            return View(comment);
        }


        // POST: Admin/comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            comment comment = db.comments.Find(id);
            db.comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/comments/Create.cshtml
@model Library.Models.comment

@{
    ViewBag.Title = "Create Comment";
}

@using (Html.BeginForm("Create", "books", FormMethod.Post, new { enctype = "multipart/form-data", @class = "user" }))
{
    @Html.AntiForgeryToken()

    <div class="card o-hidden border-0 shadow-lg">
        <div class="card-header">
            <div class="font-weight-bold text-gray-800 text-center h3">
                Add New Comment To Book in Library
                <i class="fas fa-comment"></i>
            </div>
        </div>
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="form-group row">
                            @Html.ValidationSummary(true, "", new { @class = "invalid-feedback text-danger" })
                            @Html.LabelFor(model => model.comments, htmlAttributes: new { @class = "col-sm-2 col-form-label form-control-plaintext" })
                            <div class="col-sm-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.comments, new { htmlAttributes = new { @class = "form-control " } })
                                @Html.ValidationMessageFor(model => model.comments, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.book_id,"Book Commented" ,htmlAttributes: new { @class = "control-label col-md-2 form-control-plaintext" })
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.DropDownList("book_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.book_id, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.user_id, "User Added", htmlAttributes: new { @class = "control-label col-md-2 form-control-plaintext" })
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary btn-user btn-block" />
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="pt-5">
                        <!-- Illustrations -->
                        <div class="m-0">
                            <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" style="width: 43rem;height: 27rem;margin-left:-300px;" src="~/Content/img/undraw_wall_post_83ul.svg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = " btn btn-danger text-white" })
    </div>
}

Areas/Admin/Views/comments/Details.cshtml
@model Library.Models.comment

@{
    ViewBag.Title = "Comment Details";
}


<h2>Details</h2>


<div class="card o-hidden border-0 shadow-lg">
    <div class="card-header">
        <div class="font-weight-bold text-gray-800 text-center h3">
             Comment 
            <i class="fas fa-comments"></i>
        </div>
    </div>
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-8">
                <div class="p-5">
                    <table class="table table-striped">
                        <tr class="form-group row">
                            <th class="card-title font-weight-bolder badge bg-primary text-lg ">
                                @Html.DisplayNameFor(model => model.comments)
                            </th>
                            <th class="col-md-10 mb-3 mb-sm-0 text-body text-info ">
                                @Html.DisplayFor(model => model.comments)
                            </th>
                        </tr>

                        <tr class="form-group row">
                            <td class="card-title font-weight-bolder badge bg-secondary text-lg">
                                @Html.DisplayNameFor(model => model.comment_data)
                            </td>
                            <td class="col-md-10 mb-3 mb-sm-0 text-info">
                                @Html.DisplayFor(model => model.comment_data)
                            </td>
                        </tr>

                        <tr class="form-group row">
                            <td class="card-title font-weight-bolder badge bg-success text-lg">
                                @Html.DisplayNameFor(model => model.book.title)
                            </td>
                            <td class="col-md-10 mb-3 mb-sm-0 text-info">
                                @Html.DisplayFor(model => model.book.title)

                            </td>
                        </tr>
                        <tr class="form-group row">
                            <td class="card-title font-weight-bolder badge bg-danger text-lg">
                                @Html.DisplayNameFor(model => model.user.first_name)
                            </td>
                            <td class="col-md-10 mb-3 mb-sm-0 text-info">
                                @Html.DisplayFor(model => model.user.first_name)
                            </td>
                        </tr>     
                    </table>
                </div>
                <hr>
            </div>
        </div>
    </div>
    @Html.ActionLink("Edit The Comment", "Edit", new { id = Model.comment_id }, new { @class = " btn btn-info text-white" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = " btn btn-danger text-white" })
</div>

Areas/Admin/Views/comments/Edit.cshtml
@model Library.Models.comment

@{
    ViewBag.Title = "Edit Comment";
}

@using (Html.BeginForm("Edit", "comments", FormMethod.Post, new { enctype = "multipart/form-data", @class = "user" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.comment_id)
    <div class="card o-hidden border-0 shadow-lg">
        <div class="card-header">
            <div class="font-weight-bold text-gray-800 text-center h3">
                Edit Comment To Book in Library
                <i class="fas fa-comment"></i>
            </div>
        </div>
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="form-group row">
                            @Html.ValidationSummary(true, "", new { @class = "invalid-feedback text-danger" })
                            @Html.LabelFor(model => model.comments, htmlAttributes: new { @class = "col-sm-2 col-form-label form-control-plaintext" })
                            <div class="col-sm-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.comments, new { htmlAttributes = new { @class = "form-control " } })
                                @Html.ValidationMessageFor(model => model.comments, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.book_id, "Book Commented", htmlAttributes: new { @class = "control-label col-md-2 form-control-plaintext" })
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.DropDownList("book_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.book_id, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            @Html.LabelFor(model => model.user_id, "User Added", htmlAttributes: new { @class = "control-label col-md-2 form-control-plaintext" })
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary btn-user btn-block" />
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="pt-5">
                        <!-- Illustrations -->
                        <div class="m-0">
                            <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" style="width: 43rem;height: 27rem;margin-left:-300px;" src="~/Content/img/recycle.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = " btn btn-danger text-white" })
    </div>
}

Areas/Admin/Views/comments/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Library.Models.comment>

@{
    ViewBag.Title = "All Comments";
}

<div class="card mb-4 py-3 border-bottom-secondary">
    <div class="card-body">
        <h3 class="font-weight-bold center-block text-gray-800">Comments | Display & Management</h3>
        <div class="btn btn-primary ">@Html.ActionLink("Add New One", "Create", null, new { @class = "text text-white navbar-link" }) <i class="fas fa-plus-circle fa-1x"></i></div>
    </div>
</div>
<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Comments Data</h6>
            <div class="pull-right" style="margin-right: 125px;margin-top: -23px;">
                @using (Html.BeginForm("Index", "comments", FormMethod.Get, new { @class = "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" }))
                {
                    <div class="input-group">
                        <input class="form-control bg-light border-0 small" type="search" placeholder="Search By Comment" aria-label="Search" name="search" id="CommentTxtSearch" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary hidden-sm" type="submit"><i class="fas fa-search fa-sm"></i> Search</button>
                            <button class="btn btn-primary visible-sm" type="submit"><i class="fas fa-search fa-sm"></i></button>
                        </div>
                    </div>
                }
            </div>
            <ul class="navbar-nav ml-auto">
                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                        @using (Html.BeginForm("Index", "comments", FormMethod.Get, new { @class = "form-inline mr-auto w-100 navbar-search" }))
                        {
                            <div class="input-group">
                                <input class="form-control bg-light border-0 small" type="search" placeholder="Search By Comment" aria-label="Search" name="search" id="CommentTxtSearch" aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="fas fa-search fa-sm"></i></button>
                                </div>
                            </div>
                        }
                    </div>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    @if (Model.Count() != 0)
                    {
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.First().comments)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.First().comment_data)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.First().book.title)
                                </th>
                                <th>
                                    @Html.DisplayName("User Added")
                                </th>
                                <th>
                                    @Html.DisplayName("Action")
                                </th>
                            </tr>
                        </thead>
                        foreach (var item in Model)
                        {
                            using (Html.BeginForm("Delete", "comments", new { id = item.comment_id }, FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <tbody>
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.comments)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.comment_data)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.book.title)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.user.first_name)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" Edit", "Edit", new { id = item.comment_id }, new { @class = "btn btn-primary fas fa-edit" })
                                            @Html.ActionLink(" Details", "Details", new { id = item.comment_id }, new { @class = "btn btn-info far fa-file-alt" })
                                            <input class="btn btn-danger" type="submit" value="Delete"
                                                   onclick="return confirm('Are you sure you want to delete the Comment with ID = @item.comment_id');" />
                                        </td>
                                    </tr>
                                </tbody>
                            }
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5">
                                <b class="text-danger">Sorry There Is No Comments To Show, @Html.ActionLink("Click Here To Add New One", "Create")</b>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = Request.QueryString["search"] }), /* To keep Paging when doing sorted,searched */
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })  <!--final overload To show PagedList if needed , like if there are 1 record don't need to show it .... and know current page where we are -->