Models/author.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public author()
        {
            this.books = new HashSet<book>();
        }
    
        public int author_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string nationality { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> books { get; set; }
        public HttpPostedFileBase uploadedAuthorImage { get; set; }
    }
}

Areas/Admin/Controllers/authorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using PagedList;

namespace Library.Areas.Admin.Controllers
{
    [Authorize(Roles ="Admins")]
    public class authorsController : Controller
    {
        private LibraryDBContext db = new LibraryDBContext();

        public JsonResult GetAuthors(string term)     // get Get Authors name with AutoComplete With jQuery UI
        {
            List<string> authors = db.authors.Where(x => x.first_name.ToLower().TrimStart().StartsWith(term)).Select(y => y.first_name).ToList();

            return Json(authors, JsonRequestBehavior.AllowGet);
        }

        // GET: Admin/authors
        public ActionResult Index(string search, int? page, string sortedBy)
        {
            ViewBag.SortFirstNameParameter = string.IsNullOrEmpty(sortedBy) ? "FirstName_desc" : "";    // by default sorted will be Null from this Line
            ViewBag.SortNationalityParameter = sortedBy == "Nationality" ? "Nationality_desc" : "Nationality";

            var authors = db.authors.AsQueryable(); // to allow filter in data (Where(....)) and store it in Var

            if (search != null)
            {
                authors = authors.Where(x => x.first_name.ToLower().Contains(search) || x.last_name.StartsWith(search));
            }

            switch (sortedBy)
            {
                case "FirstName_desc":
                    authors = authors.OrderByDescending(x => x.first_name);
                    break;
                case "Nationality_desc":
                    authors = authors.OrderByDescending(x => x.nationality);
                    break;
                case "Nationality":
                    authors = authors.OrderBy(x => x.nationality); // acending
                    break;
                default:
                    authors = authors.OrderBy(x => x.first_name); // acending
                    break;
            }

            return View(authors.ToList().ToPagedList(page ?? 1, 8));
        }

        // GET: Admin/authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author author = db.authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Admin/authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "author_id,first_name,last_name,nationality,uploadedAuthorImage,description")] author author)
        {
            if (ModelState.IsValid)
            {

                // Uplaod Photo =======================================================================================================
                string ImageName = Path.GetFileNameWithoutExtension(author.uploadedAuthorImage.FileName);    // get name
                string ImageExtension = Path.GetExtension(author.uploadedAuthorImage.FileName);                   // get extension
                ImageName = ImageName + '_' + DateTime.Now.ToString("yymmssfff") + ImageExtension;                // Not To Repeat
                author.photo = "~/Uploads/Photos/authors/" + ImageName;                                         // Save To DB
                ImageName = Path.Combine(Server.MapPath("~/Uploads/Photos/authors/"), ImageName);             // Combine To Local Folder
                author.uploadedAuthorImage.SaveAs(ImageName);

                db.authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Admin/authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author author = db.authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Admin/authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "author_id,first_name,last_name,nationality,uploadedAuthorImage,description")] author author)
        {
            if (ModelState.IsValid)
            {
                if (author.uploadedAuthorImage != null)
                {
                    string lastPhoto = db.authors.Find(author.author_id).photo;
                    System.IO.File.Delete(Request.MapPath(lastPhoto));  // delete From Local Folder

                    string ImageName = Path.GetFileNameWithoutExtension(author.uploadedAuthorImage.FileName);    // get name
                    string ImageExtension = Path.GetExtension(author.uploadedAuthorImage.FileName);                   // get extension
                    ImageName = ImageName + '_' + DateTime.Now.ToString("yymmssfff") + ImageExtension;                // Not To Repeat
                    author.photo = "~/Uploads/Photos/authors/" + ImageName;                                         // Save To DB
                    ImageName = Path.Combine(Server.MapPath("~/Uploads/Photos/authors/"), ImageName);             // Combine To Local Folder
                    author.uploadedAuthorImage.SaveAs(ImageName);
                }
                else
                {
                    author.photo = db.authors.Find(author.author_id).photo;     // let the last, don't change
                }

                var local = db.Set<author>().Local.FirstOrDefault(f => f.author_id == author.author_id);
                if (local != null)
                {
                    db.Entry(local).State = EntityState.Detached;
                }
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // POST: Admin/authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            author author = db.authors.Find(id);
            if (System.IO.File.Exists(Request.MapPath(author.photo)))
            {
                System.IO.File.Delete(Request.MapPath(author.photo));
            }

            db.authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/authorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;

namespace Library.Controllers
{
    [Authorize]
    public class authorController : Controller
    {
        private LibraryDBContext db = new LibraryDBContext();

        // GET: author
        public ActionResult Index()
        {
            return View(db.authors.ToList());
        }
        [AllowAnonymous]
        // GET: author/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            author author = db.authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: author/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "author_id,first_name,last_name,nationality,uploadedAuthorImage,description")] author author)
        {
            if (ModelState.IsValid)
            {

                // Uplaod Photo =======================================================================================================
                string ImageName = Path.GetFileNameWithoutExtension(author.uploadedAuthorImage.FileName);    // get name
                string ImageExtension = Path.GetExtension(author.uploadedAuthorImage.FileName);                   // get extension
                ImageName = ImageName + '_' + DateTime.Now.ToString("yymmssfff") + ImageExtension;                // Not To Repeat
                author.photo = "~/Uploads/Photos/authors/" + ImageName;                                         // Save To DB
                ImageName = Path.Combine(Server.MapPath("~/Uploads/Photos/authors/"), ImageName);             // Combine To Local Folder
                author.uploadedAuthorImage.SaveAs(ImageName);

                db.authors.Add(author);
                db.SaveChanges();
                TempData["Success"] = "Created Successfully!";
                return RedirectToAction("Index", "book");
            }

            return View(author);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/author/Create.cshtml
@model Library.Models.author

@{
    ViewBag.Title = "Create Author";
}

@using (Html.BeginForm("Create", "author", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card o-hidden border-0 shadow-lg MyBody">
        <div class="card-header h1 font-weight-bold">
            <div class="font-weight-bold text-gray-800 text-center h3">
                <h1>Create New Author In Library <i class="fas fa-user"></i></h1>
            </div>
        </div>
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="form-group row">
                            @Html.ValidationSummary(true, "", new { @class = "invalid-feedback text-danger" })
                            <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>First Name</h4></label>
                            <div class="col-sm-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control ", placeholder = "First Name ....." } })
                                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Last Name</h4></label>
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name ....." } })
                                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Nationality</h4></label>
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.nationality, new { htmlAttributes = new { @class = "form-control", placeholder = "Nationality of The author ....." } })
                                @Html.ValidationMessageFor(model => model.nationality, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h5>Description</h5></label>
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.TextAreaFor(model => model.description, new { @class = "form-control single-textarea", rows = "5", placeholder = "Description of The author ....." })
                                @Html.ValidationMessageFor(model => model.description, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>His Photo</h4></label>
                            <div class="col-md-5">
                                @Html.TextBoxFor(model => model.uploadedAuthorImage, new { type = "file", @class = "form-control-file custom-file-input", data_val_extension = "Select Only Images files", data_val_extension_extension = "jpg,png,jpeg,gif", required = true })
                                <label class="custom-file-label" for="photo">Choose file...</label>
                                @Html.ValidationMessageFor(model => model.uploadedAuthorImage, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary btn-user btn-block" />
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="pt-5">
                        <!-- Illustrations -->
                        <div class="m-0">
                            <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" src="~/Content/img/undraw_add_content_d1tf.svg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Views/author/Details.cshtml
@model Library.Models.author
@using Library.Models
@{
    ViewBag.Title = Model.first_name + " " +Model.last_name;
    LibraryDBContext db = new LibraryDBContext();
    List<book> books = db.books.ToList();
}

<section class="course_details_area section_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 course_details_left">
                <div class="main_image">
                    <img class="img-fluid img-thumbnail" src="@Url.Content(Model.photo)" alt="alt_@Model.first_name">
                </div>
                <div class="content_wrapper">
                    <h4 class="title_top">Description</h4>
                    <div class="content">
                       @Model.description
                    </div>

                    <h4 class="title">His Books</h4>
                    <div class="content">
                        <ul class="course_list">
                            @foreach (var book in books.Where(x => x.author_id == Model.author_id).ToList())
                            {
                                <li class="justify-content-between align-items-center d-flex">
                                    <p><img class="img-responsive" style="width: 70px;" src="@Url.Content(book.photo)" alt="alt_@book.title" />
                                        @book.title
                                    </p>
                                    <a class="btn_2 text-uppercase" href="~/book/Details/@book.book_id">View Details</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 right-contents">
                <div class="sidebar_top">
                    <ul>
                        <li>
                            <a class="justify-content-between d-flex">
                                <p>Author Name</p>
                                @if (Model.first_name == "Unknown")
                                {
                                    <span class="color">@Model.first_name</span>
                                }
                                else
                                {
                                    <span class="color">@Model.first_name @Model.last_name</span>
                                }
                            </a>
                        </li>
                        <li>
                            <a class="justify-content-between d-flex">
                                <p>Nationality </p>
                                <span>@Model.nationality</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <h4 class="title">Other Authors</h4>
                <div class="content">
                    <div class="comments-area mb-30">
                        <div class="comment-list">
                            @foreach (var author in db.authors.OrderByDescending(x => x.author_id).Take(5).ToList())
                            {
                                <div class="single-comment single-reviews justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb col-md-4 mb-3">
                                            <img class="img-fluid img-profile img-responsive img-rounded" style="height: 108px; width: 400px !important;" src="@Url.Content(author.photo)" alt="alt_@Model.first_name">
                                        </div>
                                        <div class="desc col-md-8">
                                            <h5>
                                                @if (Model.first_name == "Unknown")
                                                {
                                                    <a href="~/author/Details/@author.author_id">@author.first_name</a>
                                                }
                                                else
                                                {
                                                    <a href="~/author/Details/@author.author_id">@author.first_name @author.last_name</a>
                                                }
                                            </h5>
                                            <div class="rating">
                                                @author.nationality
                                            </div>
                                            <p class="comment">
                                                @author.description
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>