Models/subcategory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subcategory()
        {
            this.books = new HashSet<book>();
        }
    
        public int subcategory_id { get; set; }
        public string subcategory_name { get; set; }
        public Nullable<int> category_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<book> books { get; set; }
        public virtual category category { get; set; }
    }
}

Areas/Admin/Controllers/subcategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using PagedList;

namespace Library.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admins")]
    public class subcategoriesController : Controller
    {
        private LibraryDBContext db = new LibraryDBContext();

        public JsonResult GetSubCategories(string term)     // get Sub Categories name with AutoComplete With jQuery UI
        {
            List<string> subcategories = db.subcategories.Where(x => x.subcategory_name.ToLower().TrimStart().StartsWith(term)).Select(y => y.subcategory_name).ToList();

            return Json(subcategories, JsonRequestBehavior.AllowGet);
        }


        // GET: Admin/subcategories
        public ActionResult Index(string search, int? page, string sortedBy)
        {
            ViewBag.SortNameParameter = string.IsNullOrEmpty(sortedBy) ? "Name_desc" : "";    // by default sorted will be Null from this Line

            var subcategories = db.subcategories.AsQueryable(); // to allow filter in data (Where(....)) and store it in Var

            if (search != null)
            {
                subcategories = subcategories.Where(x => x.subcategory_name.ToLower().Contains(search));
            }

            switch (sortedBy)
            {
                case "Name_desc":
                    subcategories = subcategories.OrderByDescending(x => x.subcategory_name);
                    break;
                default:
                    subcategories = subcategories.OrderBy(x => x.subcategory_name);
                    break;
            }

            subcategories = subcategories.Include(s => s.category);
            return View(subcategories.ToList().ToPagedList(page ?? 1, 8));
        }

        // GET: Admin/subcategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            subcategory subcategory = db.subcategories.Find(id);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            return View(subcategory);
        }

        // GET: Admin/subcategories/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name");
            return View();
        }

        // POST: Admin/subcategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "subcategory_id,subcategory_name,category_id")] subcategory subcategory)
        {
            if (ModelState.IsValid)
            {
                db.subcategories.Add(subcategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", subcategory.category_id);
            return View(subcategory);
        }

        // GET: Admin/subcategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            subcategory subcategory = db.subcategories.Find(id);
            if (subcategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", subcategory.category_id);
            return View(subcategory);
        }

        // POST: Admin/subcategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "subcategory_id,subcategory_name,category_id")] subcategory subcategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.categories, "category_id", "category_name", subcategory.category_id);
            return View(subcategory);
        }


        // POST: Admin/subcategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            subcategory subcategory = db.subcategories.Find(id);
            db.subcategories.Remove(subcategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/subcategories/Create.cshtml
@model Library.Models.subcategory

@{
    ViewBag.Title = "Create Sub Category";
}

@using (Html.BeginForm("Create", "subcategories", FormMethod.Post, new { @class = "user" }))
{
    @Html.AntiForgeryToken()

    <div class="card o-hidden border-0 shadow-lg">
        <div class="card-header">
            <div class="font-weight-bold text-gray-800 text-center h3">
                Add New Sub Category To Library
                <i class="fas fa-tag"></i>
            </div>
        </div>
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="form-group row">
                            @Html.ValidationSummary(true, "", new { @class = "invalid-feedback text-danger" })
                            @Html.LabelFor(model => model.subcategory_name, htmlAttributes: new { @class = "col-sm-2 col-form-label form-control-plaintext" })
                            <div class="col-sm-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.subcategory_name, new { htmlAttributes = new { @class = "form-control " } })
                                @Html.ValidationMessageFor(model => model.subcategory_name, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.category_id, "Parent Category",htmlAttributes: new { @class = "control-label col-md-2 form-control-plaintext" })
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary btn-user btn-block" />
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="pt-5">
                        <!-- Illustrations -->
                        <div class="m-0">
                            <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" style="width: 43rem;height: 27rem;margin-left:-300px;" src="~/Content/img/undraw_collection_u2np.svg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = " btn btn-danger text-white" })
    </div>
}

Areas/Admin/Views/subcategories/Details.cshtml
@model Library.Models.subcategory

@{
    ViewBag.Title = Model.subcategory_name;
}

<h2>Details</h2>


<div class="card o-hidden border-0 shadow-lg">
    <div class="card-header">
        <div class="font-weight-bold text-gray-800 text-center h3">
            @Html.DisplayFor(model => model.subcategory_name)
            <i class="fas fa-tag"></i>
        </div>
    </div>
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-8">
                <div class="p-5">
                    <table class="table table-striped">
                            <tr class="form-group row">
                                <th class="card-title font-weight-bolder badge bg-primary text-lg ">
                                  Exist in @Html.DisplayNameFor(model => model.category.category_name)
                                </th>
                                <th class="col-md-8 mb-3 mb-sm-0 text-body text-info ">
                                    @Html.DisplayFor(model => model.category.category_name)
                                </th>
                            </tr>
                     </table>
                </div>
             <hr>
            </div>
        </div>
    </div>
    @Html.ActionLink("Edit The Sub Category", "Edit", new { id = Model.subcategory_id }, new { @class = " btn btn-info text-white" })
    @Html.ActionLink("Back to List", "Index", null, new { @class = " btn btn-danger text-white" })
</div>

Areas/Admin/Views/subcategories/Edit.cshtml
@model Library.Models.subcategory

@{
    ViewBag.Title = "Edit " + Model.subcategory_name;
}
@using (Html.BeginForm("Edit", "subcategories", FormMethod.Post, new { @class = "user" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.subcategory_id)
    <div class="card o-hidden border-0 shadow-lg">
        <div class="card-header">
            <div class="font-weight-bold text-gray-800 text-center h3">
                Add New Sub Category To Library
                <i class="fas fa-tag"></i>
            </div>
        </div>
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-8">
                    <div class="p-5">
                        <div class="form-group row">
                            @Html.ValidationSummary(true, "", new { @class = "invalid-feedback text-danger" })
                            @Html.LabelFor(model => model.subcategory_name, htmlAttributes: new { @class = "col-sm-2 col-form-label form-control-plaintext" })
                            <div class="col-sm-10 mb-3 mb-sm-0">
                                @Html.EditorFor(model => model.subcategory_name, new { htmlAttributes = new { @class = "form-control " } })
                                @Html.ValidationMessageFor(model => model.subcategory_name, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>
                        <div class="form-group row">
                            @Html.LabelFor(model => model.category_id, "Parent Category", htmlAttributes: new { @class = "control-label col-md-2 form-control-plaintext" })
                            <div class="col-md-10 mb-3 mb-sm-0">
                                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "invalid-feedback text-danger" })
                            </div>
                        </div>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary btn-user btn-block" />
                        </div>
                        <hr>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="pt-5">
                        <!-- Illustrations -->
                        <div class="m-0">
                            <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" style="width: 43rem;height: 27rem;margin-left:-300px;" src="~/Content/img/recycle.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = " btn btn-danger text-white" })
    </div>
}

Areas/Admin/Views/subcategories/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Library.Models.subcategory>

@{
    ViewBag.Title = "Sub Categories";
}

<div class="card mb-4 py-3 border-bottom-secondary">
    <div class="card-body">
        <h3 class="font-weight-bold center-block text-gray-800">Sub Categories | Display & Management</h3>
        <div class="btn btn-primary ">@Html.ActionLink("Add New One", "Create", null, new { @class = "text text-white navbar-link" }) <i class="fas fa-plus-circle fa-1x"></i></div>
    </div>
</div>
<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Sub Categories Data</h6>
            <div class="pull-right" style="margin-right: 125px;margin-top: -23px;">
                @using (Html.BeginForm("Index", "subcategories", FormMethod.Get, new { @class = "d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search" }))
                {
                    <div class="input-group">
                        <input class="form-control bg-light border-0 small" type="search" placeholder="Search By Sub Category" aria-label="Search" name="search" id="SubCategoryTxtSearch" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary hidden-sm" type="submit"><i class="fas fa-search fa-sm"></i> Search</button>
                            <button class="btn btn-primary visible-sm" type="submit"><i class="fas fa-search fa-sm"></i></button>
                        </div>
                    </div>
                }
            </div>
            <ul class="navbar-nav ml-auto">
                <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                <li class="nav-item dropdown no-arrow d-sm-none">
                    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-search fa-fw"></i>
                    </a>
                    <!-- Dropdown - Messages -->
                    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                        @using (Html.BeginForm("Index", "books", FormMethod.Get, new { @class = "form-inline mr-auto w-100 navbar-search" }))
                        {
                            <div class="input-group">
                                <input class="form-control bg-light border-0 small" type="search" placeholder="Search By Sub Category" aria-label="Search" name="search" id="SubCategoryTxtSearch" aria-describedby="basic-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="fas fa-search fa-sm"></i></button>
                                </div>
                            </div>
                        }
                    </div>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    @if (Model.Count() != 0)
                    {
                        <thead>
                            <tr>
                                <th>
                                    @Html.ActionLink("Sub Category Name", "Index", new { sortedBy = ViewBag.SortNameParameter, search = Request.QueryString["search"] })
                                    <i class="fas fa-sort"></i>
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.First().category.category_name)
                                </th>
                                <th>
                                    @Html.DisplayName("Action")
                                </th>
                            </tr>
                        </thead>
                        foreach (var item in Model)
                        {
                            using (Html.BeginForm("Delete", "subcategories", new { id = item.subcategory_id }, FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()
                                <tbody>
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.subcategory_name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.category.category_name)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" Edit", "Edit", new { id = item.subcategory_id }, new { @class = "btn btn-primary fas fa-edit" })
                                            @Html.ActionLink(" Details", "Details", new { id = item.subcategory_id }, new { @class = "btn btn-info far fa-file-alt" })
                                            <input class="btn btn-danger" type="submit" value="Delete"
                                                   onclick="return confirm('Are you sure you want to delete the Sub Category with ID = @item.subcategory_id');" />
                                        </td>
                                    </tr>
                                </tbody>
                            }
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5">
                                <b class="text-danger">Sorry There Is No Sub Category To Show, @Html.ActionLink("Click Here To Add New One", "Create")</b>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@Html.PagedListPager(Model, page => Url.Action("Index", new { page, search = Request.QueryString["search"], sortedBy = Request.QueryString["sortedBy"] }), /* To keep Paging when doing sorted,searched */
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })  <!--final overload To show PagedList if needed , like if there are 1 record don't need to show it .... and know current page where we are -->