Models/book.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int book_id { get; set; }
        public string title { get; set; }
        public string edition { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> publication_id { get; set; }
        public string photo { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> subcategory_id { get; set; }
        public Nullable<int> pages { get; set; }
        public string description { get; set; }
        public string add_date { get; set; }
        public Nullable<byte> rate { get; set; }
        public Nullable<byte> availabilty { get; set; }
        public Nullable<int> member_id { get; set; }
        public string tags { get; set; }
        public string File { get; set; }
    
        public virtual author author { get; set; }
        public virtual publication publication { get; set; }
        public virtual subcategory subcategory { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }

        public HttpPostedFileBase uploadedImage { get; set; }

        public HttpPostedFileBase uploadedFile { get; set; }
        public int Category_Id { get; set; }
    }
}

Areas/Admin/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library.Models;
using PagedList;

namespace Library.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admins")]
    public class booksController : Controller
    {
        private LibraryDBContext db = new LibraryDBContext();

        public JsonResult GetBooks(string term)     // get books name with AutoComplete With jQuery UI
        {
            List<string> books = db.books.Where(x => x.title.ToLower().TrimStart().StartsWith(term)).Select(y => y.title).ToList();

            return Json(books, JsonRequestBehavior.AllowGet);
        }


        // GET: Admin/books
        public ActionResult Index(string search , int? page, string sortedBy)
        {

            ViewBag.SortTitleParameter = string.IsNullOrEmpty(sortedBy) ? "Title_desc" : "";    // by default sorted will be Null from this Line
            ViewBag.SortPriceParameter = sortedBy == "Price" ? "Price_desc" : "Price";
            ViewBag.SortPagesNumberParameter = sortedBy == "Pages_Number" ? "Pages_Number_desc" : "Pages_Number";
            ViewBag.SortAddedDateParameter = sortedBy == "Added_Date" ? "Added_Date_desc" : "Added_Date";
            ViewBag.SortRateParameter = sortedBy == "Rate" ? "Rate_desc" : "Rate";

            var books = db.books.AsQueryable(); // to allow filter in data (Where(....)) and store it in Var

            if (search != null)
            {
                books = books.Where(x => x.title.ToLower().Contains(search));
            }

            switch (sortedBy)
            {
                case "Title_desc":
                    books = books.OrderByDescending(x => x.title);
                    break;
                case "Price_desc":
                    books = books.OrderByDescending(x => x.price);
                    break;
                case "Price":
                    books = books.OrderBy(x => x.price); // acending
                    break;
                case "Pages_Number_desc":
                    books = books.OrderByDescending(x => x.pages);
                    break;
                case "Pages_Number":
                    books = books.OrderBy(x => x.pages); // acending
                    break;
                case "Added_Date_desc":
                    books = books.OrderByDescending(x => x.add_date);
                    break;
                case "Added_Date":
                    books = books.OrderBy(x => x.add_date); // acending
                    break;
                case "Rate_desc":
                    books = books.OrderByDescending(x => x.rate);
                    break;
                case "Rate":
                    books = books.OrderBy(x => x.rate); // acending
                    break;
                default:
                    books = books.OrderBy(x => x.title); // acending
                    break;
            }

            books = books.Include(b => b.author).Include(b => b.publication).Include(b => b.subcategory).Include(b => b.user);
            return View(books.ToList().ToPagedList(page ?? 1, 8));
        }

        // GET: Admin/books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            book book = db.books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Admin/books/Create
        public ActionResult Create()
        {
            ViewBag.author_id = new SelectList(db.authors, "author_id", "first_name");
            ViewBag.publication_id = new SelectList(db.publications, "publication_id", "name");
            ViewBag.subcategory_id = new SelectList(db.subcategories, "subcategory_id", "subcategory_name");
            ViewBag.member_id = new SelectList(db.users, "Id", "first_name");
            return View();
        }

        // POST: Admin/books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "book_id,title,edition,price,publication_id,author_id,subcategory_id,pages,description,rate,availabilty,member_id,tags,uploadedImage,uploadedFile")] book book)
        {
            if (ModelState.IsValid)
            {
                book.add_date = DateTime.Now.ToString();                                                    // Data

                // Uplaod Photo =======================================================================================================
                string ImageName = Path.GetFileNameWithoutExtension(book.uploadedImage.FileName);    // get name
                string ImageExtension = Path.GetExtension(book.uploadedImage.FileName);                   // get extension
                ImageName = ImageName + '_' + DateTime.Now.ToString("yymmssfff") + ImageExtension;                // Not To Repeat
                book.photo = "~/Uploads/Photos/books/" + ImageName;                                         // Save To DB
                ImageName = Path.Combine(Server.MapPath("~/Uploads/Photos/books/"), ImageName);             // Combine To Local Folder
                book.uploadedImage.SaveAs(ImageName);                                                       // Move it

                // Uplaod File =======================================================================================================
                string FileName = Path.GetFileNameWithoutExtension(book.uploadedFile.FileName);             // get name
                string FileExtension = Path.GetExtension(book.uploadedFile.FileName);                       // get extension
                FileName = FileName + '_' + DateTime.Now.ToString("yymmssfff") + FileExtension;                   // Not To Repeat
                book.File = "~/Uploads/Books/" + FileName;                                                  // Save To DB
                FileName = Path.Combine(Server.MapPath("~/Uploads/Books/"), FileName);                      // Combine To Local Folder
                book.uploadedFile.SaveAs(FileName);                                                         // Move it 

                db.books.Add(book);
                db.SaveChanges();
                TempData["Success"] = "Created Successfully!";
                return RedirectToAction("Index");
            }

            ViewBag.author_id = new SelectList(db.authors, "author_id", "first_name", book.author_id);
            ViewBag.publication_id = new SelectList(db.publications, "publication_id", "name", book.publication_id);
            ViewBag.subcategory_id = new SelectList(db.subcategories, "subcategory_id", "subcategory_name", book.subcategory_id);
            ViewBag.member_id = new SelectList(db.users, "Id", "first_name", book.member_id);
            return View(book);
        }

        // GET: Admin/books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            book book = db.books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.author_id = new SelectList(db.authors, "author_id", "first_name", book.author_id);
            ViewBag.publication_id = new SelectList(db.publications, "publication_id", "name", book.publication_id);
            ViewBag.subcategory_id = new SelectList(db.subcategories, "subcategory_id", "subcategory_name", book.subcategory_id);
            ViewBag.member_id = new SelectList(db.users, "Id", "first_name", book.member_id);
            return View(book);
        }

        // POST: Admin/books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "book_id,title,edition,price,publication_id,author_id,subcategory_id,pages,description,add_date,rate,availabilty,member_id,tags,uploadedImage,uploadedFile")] book book)
        {
            if (ModelState.IsValid)
            {
                // Uplaod Photo =======================================================================================================

                if (book.uploadedImage != null)
                {
                    string lastPhoto = db.books.Find(book.book_id).photo;
                    System.IO.File.Delete(Request.MapPath(lastPhoto));  // delete From Local Folder

                    string ImageName = Path.GetFileNameWithoutExtension(book.uploadedImage.FileName);           // get name
                    string ImageExtension = Path.GetExtension(book.uploadedImage.FileName);                     // get extension
                    ImageName = ImageName + '_' + DateTime.Now.ToString("yymmssfff") + ImageExtension;                // Not To Repeat
                    book.photo = "~/Uploads/Photos/books/" + ImageName;                                         // Save To DB
                    ImageName = Path.Combine(Server.MapPath("~/Uploads/Photos/books/"), ImageName);             // Combine To Local Folder
                    book.uploadedImage.SaveAs(ImageName);                                                       // Move it
                }
                else
                {
                    book.photo = db.books.Find(book.book_id).photo;     // let the last, don't change
                }

Controllers/bookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Library.Models;
using PagedList;

namespace Library.Controllers
{
    public class bookController : Controller
    {
        private LibraryDBContext db = new LibraryDBContext();
        public JsonResult GetBooks(string term)     // get books name with AutoComplete With jQuery UI
        {
            List<string> books = db.books.Where(x => x.title.ToLower().TrimStart().StartsWith(term)).Select(y => y.title).ToList();

            return Json(books, JsonRequestBehavior.AllowGet);
        }

        // GET: book
        public ActionResult Index(int? page, string searched)
        {
            if (searched != null)
            {
                return View(db.books.Where(x => x.title.ToLower().Contains(searched)).ToList().ToPagedList(page ?? 1, 8));
            }
            else
            {
                var books = db.books.Include(b => b.author).Include(b => b.publication).Include(b => b.subcategory).Include(b => b.user);
                return View(books.OrderByDescending(x=>x.book_id).ToList().ToPagedList(page ?? 1, 8));
            }
        }

        // GET: book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            book book = db.books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: book/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.author_id = new SelectList(db.authors, "author_id", "first_name");
            ViewBag.publication_id = new SelectList(db.publications, "publication_id", "name");
            ViewBag.subcategory_id = new SelectList(db.subcategories, "subcategory_id", "subcategory_name");
            ViewBag.member_id = new SelectList(db.users, "Id", "first_name");

            return View();
        }

        // POST: book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "book_id,title,edition,price,publication_id,author_id,subcategory_id,pages,description,rate,availabilty,tags,uploadedImage,uploadedFile")] book book)
        {
            if (ModelState.IsValid)
            {
                book.add_date = DateTime.Now.ToString();                                                    // Data
                var userName = User.Identity.GetUserName();
                book.member_id = db.users.Where(x=>x.UserName == userName).Select(x=>x.Id).FirstOrDefault();

                // Uplaod Photo =======================================================================================================
                string ImageName = Path.GetFileNameWithoutExtension(book.uploadedImage.FileName);    // get name
                string ImageExtension = Path.GetExtension(book.uploadedImage.FileName);                   // get extension
                ImageName = ImageName + '_' + DateTime.Now.ToString("yymmssfff") + ImageExtension;                // Not To Repeat
                book.photo = "~/Uploads/Photos/books/" + ImageName;                                         // Save To DB
                ImageName = Path.Combine(Server.MapPath("~/Uploads/Photos/books/"), ImageName);             // Combine To Local Folder
                book.uploadedImage.SaveAs(ImageName);                                                       // Move it

                // Uplaod File =======================================================================================================
                string FileName = Path.GetFileNameWithoutExtension(book.uploadedFile.FileName);             // get name
                string FileExtension = Path.GetExtension(book.uploadedFile.FileName);                       // get extension
                FileName = FileName + '_' + DateTime.Now.ToString("yymmssfff") + FileExtension;                   // Not To Repeat
                book.File = "~/Uploads/Books/" + FileName;                                                  // Save To DB
                FileName = Path.Combine(Server.MapPath("~/Uploads/Books/"), FileName);                      // Combine To Local Folder
                book.uploadedFile.SaveAs(FileName);                                                         // Move it 

                db.books.Add(book);
                db.SaveChanges();
                TempData["Success"] = "Created Successfully!";
                return RedirectToAction("Index");
            }

            ViewBag.author_id = new SelectList(db.authors, "author_id", "first_name", book.author_id);
            ViewBag.publication_id = new SelectList(db.publications, "publication_id", "name", book.publication_id);
            ViewBag.subcategory_id = new SelectList(db.subcategories, "subcategory_id", "subcategory_name", book.subcategory_id);
            ViewBag.member_id = new SelectList(db.users, "Id", "first_name", book.member_id);
            return View(book);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/book/Create.cshtml
@model Library.Models.book

@{
    ViewBag.Title = "Create book";
}



<div class="card o-hidden border-0 shadow-lg MyBody">
    <div class="card-header h1 font-weight-bold">
        <div class="font-weight-bold text-gray-800 text-center h4">
            <h1>Add New Book To Library <i class="fas fa-book"></i></h1>
        </div>
    </div>
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-7">
                @using (Html.BeginForm("Create", "book", FormMethod.Post, new { enctype = "multipart/form-data", @class = "user" ,id="MyForm"}))
                {
                    @Html.AntiForgeryToken()
                <div class="p-5">
                    <div class="form-group row">
                        @Html.ValidationSummary(true, "", new { @class = "invalid-feedback text-danger" })
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Book Title</h4></label>
                        <div class="col-sm-10 mb-3 mb-sm-0">
                            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control ", placeholder = "Title Of the Book ....." } })
                            @Html.ValidationMessageFor(model => model.title, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Edition</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.EditorFor(model => model.edition, new { htmlAttributes = new { @class = "form-control", placeholder = "Edition Of the Book ....." } })
                            @Html.ValidationMessageFor(model => model.edition, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Price</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", placeholder = "Price Of the Book ....." } })
                            @Html.ValidationMessageFor(model => model.price, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Publication</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.DropDownList("publication_id", null, htmlAttributes: new { @class = "form-control dropdown default-select", placeholder = "Publication Of the Book ....." }) <a class="btn btn-info" href="~/publication/Create"><i class="fas fa-plus"> Add Publication</i></a>
                            @Html.ValidationMessageFor(model => model.publication_id, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Author</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.DropDownList("author_id", null, htmlAttributes: new { @class = "form-control dropdown default-select", placeholder = "Author Of the Book ....." }) <a class="btn btn-info" href="~/publication/Create"><i class="fas fa-plus"> Add Author</i></a>
                            @Html.ValidationMessageFor(model => model.author_id, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Category</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.DropDownList("subcategory_id", null, htmlAttributes: new { @class = "form-control dropdown default-select", placeholder = "Category Of the Book ....." })
                            @Html.ValidationMessageFor(model => model.subcategory_id, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Pages</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.EditorFor(model => model.pages, new { htmlAttributes = new { @class = "form-control", placeholder = "Number Of Page ....." } })
                            @Html.ValidationMessageFor(model => model.pages, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h5>Description</h5></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.TextAreaFor(model => model.description, new { @class = "form-control single-textarea", rows = "5", placeholder = "Description Of the book", onfocus = "this.placeholder = ''", onblur = "this.placeholder = 'Message'" })
                            @Html.ValidationMessageFor(model => model.description, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Tags</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.EditorFor(model => model.tags, new { htmlAttributes = new { @class = "form-control tags ", placeholder = "Seperate between each tag with (,)" } })
                            @Html.ValidationMessageFor(model => model.tags, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Availablity</h4></label>
                        <div class="col-md-10 custom-control custom-radio mb-3">
                            @Html.RadioButton("availabilty", 1, true) Yes
                            @Html.RadioButton("availabilty", 2) No
                            @Html.ValidationMessageFor(model => model.availabilty, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h5>Rate Of The Book</h5></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.DropDownList("rate", new List<SelectListItem>
                            {
                                new SelectListItem {Text = "Bad",Value = "1"},
                                new SelectListItem {Text = "Good",Value = "2"},
                                new SelectListItem {Text = "Very Good",Value = "3"},
                                new SelectListItem {Text = "Excellent",Value = "4"}
                            }, "Rate Of The Book", new { @class = "form-control dropdown default-select" })
                            @Html.ValidationMessageFor(model => model.rate, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h5>Book Cover</h5></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.TextBoxFor(model => model.uploadedImage, new { type = "file", @class = "form-control-file custom-file-input", data_val_extension = "Select Only Images files", data_val_extension_extension = "jpg,png,jpeg,gif", required = true })
                            <label class="custom-file-label" for="photo">Choose file...</label>
                            @Html.ValidationMessageFor(model => model.uploadedImage, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label form-control-plaintext h1 font-weight-bold"><h4>Book File</h4></label>
                        <div class="col-md-10 mb-3 mb-sm-0">
                            @Html.TextBoxFor(model => model.uploadedFile, new { type = "file", @class = "form-control-file custom-file-input", data_val_extension = "Select Only PDF files", data_val_extension_extension = "pdf", required = true })
                            <label class="custom-file-label" for="file">Choose file...</label>
                            @Html.ValidationMessageFor(model => model.uploadedFile, "", new { @class = "invalid-feedback text-danger" })
                        </div>
                    </div>
                    <div class="col-md-offset-2 col-md-10 mt-3">
                        <input type="submit" value="Create" id="btnSubmit" class="btn btn-primary btn-user btn-block" />
                    </div>
                    <div style="text-align:center;display:none" id="loaderDiv">
                        <img src="~/Images/loading.gif" />
                    </div>
                    <hr>
                </div>
                }
                </div>
            <div class="col-lg-5">
                <div class="pt-5">
                    <!-- Illustrations -->
                    <div class="m-0">
                        <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" src="~/Content/img/undraw_Bibliophile_hwqc.svg" alt="">
                    </div>
                    <div class="m-0">
                        <img class="hidden-sm hidden-xs px-3 px-sm-4 mt-3 mb-4" src="~/Content/img/undraw_Books_l33t.svg" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>